title = "My software engineering journey"
base_url = "https://carlosvin.github.io"
description = "Documenting a personal journey through software engineering, AI, and programming. This blog features deep dives, practical guides, and recent learnings for both seasoned and aspiring developers."
author = "Carlos Martin Sanchez"

compile_sass = false
build_search_index = true
generate_sitemap = true
generate_robots_txt = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
ignored_content = ["**/node_modules/*", "**/.github/*"]

[search]
index_format = "elasticlunr_json"

[markdown]
render_emoji = true
# Whether to highlight code blocks found in Markdown files.
[markdown.highlighting]
theme = "solarized-light"

[[taxonomies]]
name = "tags"
paginate_by = 10

[extra]
nav_sections = [{ path = "about", title = "About" }]
preview_image = "/img/android-chrome-192x192.png"
og_locale = "en_US"

[[extra.social_links]]
name = "GitHub"
url = "https://github.com/carlosvin"
icon = "github"

[[extra.social_links]]
name = "LinkedIn"
url = "https://linkedin.com/in/carlosvin"
icon = "linkedin"

[[extra.social_links]]
name = "RSS"
url = "https://carlosvin.github.io/atom.xml"
icon = "rss"
