# baseURL = 'https://carlosvin.github.io/'
languageCode = 'en'
title = 'Carlos says bla bla'
# theme = 'PaperMod'
theme = 'ananke'
site_logo = "/favicon.png"

[params]
show_reading_time = true
custom_css = ["fonts/style.css", "custom.css"]

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/carlosvin"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/carlosvin"
[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/carlosvin"

[languages]
  [languages.es]
    disabled = false
    languageCode = 'es-ES'
    languageDirection = 'ltr'
    languageName = 'Spanish'
    title = 'Carlos dice bla bla'
    weight = 1
    [languages.es.params]
      subtitle = 'Tech stuff'
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Carlos says bla bla'
    weight = 2
    [languages.en.params]
      subtitle = 'Tech stuff'

[security]
enableInlineShortcodes = false

[security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
[security.exec]
    allow = ['^asciidoctor$']
    osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[markup]
  [markup.asciidocExt]
      workingFolderCurrent = true
      # preserveTOC = true
      [markup.asciidocExt.attributes]
          allow-uri-read = ""
          source-highlighter = "rouge"
          rouge-css = "style"
          rouge-style = "thankful_eyes"
          imagesdir = "/images"
          icons = "font"
  [markup.tableOfContents]
  ordered = true


