= Elegir tecnologías para mi nuevo proyeco C++
:date: 2017-09-24
:updated: 2020-06-13
:keywords: C++, Unit Testing, Build System, Build Software, Meson, Catch, doctest
:description: Las razones por las que he elegido Meson+Doctest para crear un proyecto en C++. También contiene un ejemplo fácil de ejecutar y de reutilizar como template.
:lang: es
:toc:
:make_link: https://www.gnu.org/software/make/manual/make.html[Make,window=_blank]
:maven: https://maven.apache.org/[Maven,window=_blank]
:scons: https://scons.org/[Scons,window=_blank]
:cmake: https://cmake.org/[CMake,window=_blank]
:meson: https://mesonbuild.com/[Meson,window=_blank]
:gradle: https://gradle.org/[Gradle,window=_blank]
:autotools: https://www.gnu.org/software/automake/manual/html_node/Autotools-Introduction.html[Autotools,window=_blank]
:gnome: https://www.gnome.org/[Gnome,window=_blank]
:ninja: https://ninja-build.org/[Ninja,window=_blank]
:python: https://python.org/[Python,window=_blank]
:catch: https://github.com/philsquared/Catch[Catch,window=_blank]
:doctest: https://github.com/onqtam/doctest[doctest,window=_blank]
:xunit: https://en.wikipedia.org/wiki/XUnit[xUnit,window=_blank]
:bdd: https://en.wikipedia.org/wiki/Behavior-driven_development[BDD,window=_blank]
:uuid: https://en.wikipedia.org/wiki/Universally_unique_identifier[UUID,window=_blank]
:mt19937:  https://www.cplusplus.com/reference/random/mt19937[mt19937,window=_blank]
:benchmarkresults: https://github.com/onqtam/doctest/blob/master/doc/markdown/benchmarks.md[resultados de las comparaciones de rendimiento]

Estoy empezando un pequeño proyecto en C++ y antes de nada me han surgido un par de preguntas:

. ¿Cómo voy a construirlo?
. ¿Qué framework para pruebas unitarias utilizar?

TIP: Si simplemente quieres comenzar un proyecto en C++, fácil de construir, con una librería y pruebas unitarias listas, simplemente visita el repositorio del proyecto de ejemplo https://github.com/carlosvin/uuid-cpp y sigue las https://github.com/carlosvin/uuid-cpp/blob/master/README.md[instrucciones en el README.md,window=blank_].


== Elegir un Sistema de Construcción ({meson})

Ya he utilizado antes {make_link}, {maven}, {scons}, {gradle} y {autotools}, pero tengo algunas razones para probar algo diferente, hay algunas cosas que no me gustan:

{autotools}::
  No es fácil de configurar y mantener: hay distintos ficheros de configuración y distintos pasos de configuración.
{gradle}::
  La construcción de proyectos C++ está todavía en desarrollo, los modelos y APIs están cambiando. No es muy rápido. Puedes ver un ejemplo en este artículo link:/posts/gradle-cpp/{lang}[Construir un proyecto Cpp con Gradle].
{make_link}::
  A medida que el proyecto crece los archivos de configuración se van complicando y volviendo poco manejables. La sintáxis no me parece clara (esto es una custión de gustos).
{scons}::
  Es más lento y un poco más difícil de comprender que {meson}.
{maven}::
  Es lento y puedes terminar "_Javatizando_" la estructura del proyecto.

NOTE: He nombrado solo las cosas que no gustan, pero estos sistemas de construcción tienen otras grandes virtudes, personalmente me encantan {gradle}, {autotools} y {maven} (solo para projectos Java).

=== {cmake} vs {meson}

Después de descartar los anteriores, estoy considerando {meson} y {cmake}. Los dos son bastante rápidos:

Aunque {meson} está hecho en {python}, simplemente genera projectos {ninja}. La primera vez tenemos que ejecutar {meson} para configurar el proyecto, el resto de ejecuciones para compilar o ejecutar pruebas, realmente estaremos ejecutando directamente {ninja}.

{cmake} también puede generar proyectos {ninja} entre otros formatos, https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html[mira la documentación "CMake generators"].

{cmake}::
  Tiene una gran ventaja sobre {meson}, es mucho más maduro y es mucho más usado, lo que significa que podrás encontrar muy fácilmente ejemplos, documentación y ayuda en Internet. No importa el tipo de proyecto que estés empezando, lo más seguro es que {cmake} sea una buena elección.
{meson}::
  Es un proyecto jóven comparado con {cmake}, pero está creciendo rápido y ya ha sido adoptado por algunos proyectos importantes como {gnome}, donde han comenzado una iniciativa para https://wiki.gnome.org/Initiatives/GnomeGoals/MesonPorting[migrar desde Autotools a Meson].

*Finalmente he elegido* {meson} porque:

* La sintáxis es muy clara para mí, cuando leo un archivo [.title-ref]#meson.build# entiendo rápidamente lo ue está pasando durante el proceso de construcción.
* Es rápido, aunque está escrito en {python} utiliza {ninja} para construir el proyecto. La primera vez tienes que utilizar {meson} para configurar el proyecto, pero para construir y probar el proyecto relmente estamos ejecutando {ninja}.

.Pasos para compilar y ejectuar tests
[source,bash]
----
$ meson build . <1>
$ cd build
$ ninja build   <2>
$ ninja test    <3>
----
<1> Primera vez, configuración del proyecto
<2> Cada vez que construyes el projecto
<3> Cada vez que ejecutas tests

=== Otras comparaciones entre sistemas de construcción
He encontrado un par de comparaciones interesantes entre algunos de los sistemas de construcción en C++, aunque puede que no sean del todo imparciales porque han sido realizadas por {meson} y {scons}.

* https://bitbucket.org/scons/scons/wiki/SconsVsOtherBuildTools[C++ build systems comparison from Scons].
* https://mesonbuild.com/Simple-comparison.html[C++ build systems comparison from Meson].

== Framework the Pruebas Unitarias

Anteriorment he utilizado algunas librerías del tipo {xunit} como https://github.com/unittest-cpp/unittest-cpp[UnitTest++], https://cpputest.github.io/[CppUTest] o https://github.com/google/googletest[Google Test] que encaja perfectamente con https://github.com/google/googletest/tree/master/googlemock[Google Mock].

Si quires una apuesta segura que cumpla tus expectativas, te recomiendo https://github.com/google/googletest[Google Test].

Pero hace algún tiempo encontré un framework de pruebas con algunas características no tan comunes en librerías de pruebas C++ y que resultaba realmente fácil de utilizar, estoy hablando de {catch}:

* Es simplemente un fichero de cabeceras C++ sin dependencias adicionales, por lo que resulta realmente rápido comenzar (wget y utilizar el fichero descargado desde tus pruebas).
* Puedes utilizar el estilo normal de pruebas unitarias o el estilo {bdd}.

Si quieres saber más sobre {catch}, te recomiendo que directamente lo pruebes, el siguiente ejemplo, es cuestión de dos minutos https://github.com/philsquared/Catch/blob/master/docs/tutorial.md#writing-tests[simple example up and running]. Puedes también leer algunos artículos como https://github.com/philsquared/Catch/blob/master/docs/why-catch.md[Why do we need yet another C++ test framework?] o https://blog.coldflake.com/posts/Testing-C++-with-a-new-Catch/[Testing C++ With A New Catch].

=== {doctest}: Una alternativa a {catch}

Hay otro framework de pruebas llamado {doctest}, con los mismos principios que {catch}, pero promete ser más rápido y ligero ({benchmarkresults}) que {catch}.

{doctest} fue diseñado basándose en los puntos fuertes de {catch}, pero hay algunas https://github.com/onqtam/doctest/blob/master/doc/markdown/faq.md#how-is-doctest-different-from-catch[diferencias].

No es fácil decidirse por uno, los dos son muy parecidos, puedes comprobar las diferencias a continuación:

.Differencias entre la rama usando {doctest} y la rama usando {catch}
[source,diff]
----
@@ -1,12 +1,12 @@
-#define CATCH_CONFIG_MAIN // It tells Catch to provide a main() - only do this in one cpp file
+#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

-#include "catch.hpp"
+#include "doctest.h"
#include "Uuid.h"
#include <string>

constexpr int MAX_ITERS = 100;

-TEST_CASE("Uuid", "[uuid]")
+TEST_CASE("Uuid")
{
for (int i = 0; i < MAX_ITERS; i++)
{
@@ -26,7 +26,7 @@ TEST_CASE("Uuid", "[uuid]")

// BDD style

-SCENARIO("UUID creation", "[Uuid]")
+SCENARIO("UUID creation")
{

GIVEN("A random UUID ")
----

Finalmente he elegido {doctest} simplemente porque es más rápido: {benchmarkresults}.

NOTE: He creado el proyecto de ejemplo utilizando ambos frameworks, puedes encontrarlos en diferentes ramas del repositorio: https://github.com/carlosvin/uuid-cpp/tree/doctest[rama doctest] or https://github.com/carlosvin/uuid-cpp/tree/catch[rama catch].

== Ejemplo

He creado un ejemplo para ilustrar este artículo: https://github.com/carlosvin/uuid-cpp.

Consiste en una implementación básica de un generador pseudo-aleatorio de {uuid}, está basado en {mt19937} que no es criptográficamente seguro.

=== Artefactos del Proyecto

Cuando instalemos el proyecto, {meson} ({ninja} realmente) generará una serie de artefactos en nuestro sistema.

* Librería compartida: `+libuuid+`.
* Fichero de cabeceras para que los desarrolladores puedan usar la librería: `+include/Uuid.h+`.
* Fichero ejecutable `+uuidgen+` (Generador de {uuid}).
* Ejecutable de las pruebas unitarias (no será instalado).

Si ejecutamos `+ninja install+` en Linux obtendremos los siguientes ficheros:

[source,bash]
----
/usr/local/lib/libuuid.so
/usr/local/include/Uuid.h
/usr/local/bin/uuidgen
----

=== Estructura del Proyecto (https://github.com/carlosvin/uuid-cpp[Fork project])

https://github.com/carlosvin/uuid-cpp/blob/master/meson.build[meson.build]:: Fichero principal de configuración para construir el proyecto. 
Lo utilizamos para especificar las propiedades y subdirectorios del proyecto.

.meson.build
[source,python]
----
project(
    'cpp-meson-example', # project name
    'cpp', # C++ project, e.g: for C project 
    version : '1.0.0',
    license : 'MIT',
    default_options : ['cpp_std=c++11']) # compile for C++

# it will be referred from subdir projects
inc = include_directories('include') 

# meson will try to find a meson.build file inside following directories
subdir('include')
subdir('src')
subdir('test')
----

https://github.com/carlosvin/uuid-cpp/blob/master/include/[include]::
  meson.build;;
    Archivo de configuración para construir este directorio, no hay mucho que hacer aquí, simplemente indicamos qué ficheros de cabeceras han de ser instalados

.include/meson.build
[source,python]
----
# Select header files to be installed 
install_headers('Uuid.h')
----

  https://github.com/carlosvin/uuid-cpp/blob/master/include/Uuid.h[Uuid.h];;
    Archivos de cabeceras, es el interfaz que expone la librería y que será incluido por los usuarios de la misma.
  
.include/Uuid.h
[source,cpp]
----
namespace ids {

class Uuid {
    private:
    // ...
----

https://github.com/carlosvin/uuid-cpp/blob/master/src[src]::
  https://github.com/carlosvin/uuid-cpp/blob/master/src/meson.build[meson.build (src)];; Declara 2 artefactos de salida: La librería `libuuid` y el ejecutable `uuidgen`.

.src/meson.build
[source,python]
----
libuuid = shared_library(
    'uuid', <1>
    'Uuid.cpp', <2> 
    include_directories : inc, <3>
    install : true) <4>

uuidgen = executable(
    'uuidgen', <5>
    'main.cpp', <6>
    include_directories : inc, <7>
    link_with : libuuid, <8>
    install : true) <9>
----
<1> library name
<2> source files to be compile
<3> previously declared include directories in root `meson.build`
<4> `libuuid` will be part of project installation
<5> executable name
<6> source files to compile
<7> previously declared include directories in root `meson.build`
<8> linking executable with shared previously declared shared library `libuuid`
<9> `uuidgen` executable be part of project installation

  https://github.com/carlosvin/uuid-cpp/blob/master/src/main.cpp[main.cpp];; Código fuente del ejecutable de la aplicación: `uuidgen`

.src/main.cpp
[source,cpp]
----
#include "Uuid.h"
#include <iostream>

int main() 
{
    ids::Uuid uuid;
    std::cout << uuid.to_str() << std::endl;
    return 0;
}
----
  
  https://github.com/carlosvin/uuid-cpp/blob/master/src/Uuid.cpp[Uuid.cpp];; Implementación de la clase declarada en el fichero de cabeceras `Uuid.h`.

.src/Uuid.cpp
[source,cpp]
----
#include "Uuid.h"

Uuid::Uuid()
{ // ...
----

https://github.com/carlosvin/uuid-cpp/blob/master/test/[test]::
  https://github.com/carlosvin/uuid-cpp/blob/master/test/meson.build[meson.build (test)];;
    Archivo de configuración para construir y ejecutar las pruebas unitarias.

.test/meson.build
[source,python]
----
testexe = executable(
    'testexe', <1>
    'uuid_test.cpp', <2>
    include_directories : inc, <3>
    link_with : libuuid) <4>

test('Uuid test', testexe) <5>

test('Uuid test with args and env', testexe, args : ['arg1', 'arg2'], env : ['FOO=bar']) <6>
----
<1> test executable name
<2> tests source files to be compiled
<3> declared include directories in root `meson.build`
<4> link test executable with previously declared shared library `libuuid`
<5> test execution
<6> we can specify other test execution passing arguments or environment variables

  doctest.h;;
    Librería {doctest} en un único fichero de cabeceras. Puedes tratar de automatizar el proceso de instalación de la librería, yo por el momento la he instalado manualmente, ya que es un proceso muy sencillo:

.Añadir {doctest} al proyecto
[source,bash]
----
cd test
wget https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h 
----

  https://github.com/carlosvin/uuid-cpp/blob/master/test/uuid_test.cpp[uuid_test.cpp];;
    Implementación de las pruebas unitarias.

.test/uuid_test.cpp
[source,cpp]
----
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "doctest.h"
#include "Uuid.h"
#include <string>

constexpr int MAX_ITERS = 100;

TEST_CASE("Uuid")
{
    for (int i = 0; i < MAX_ITERS; i++)
    {
        ids::Uuid uuid;
        std::string uuid_str{uuid.to_str()};

        INFO(uuid_str);

        // If assertion fails test execution is stopped
        REQUIRE(uuid_str.size() == 36);

        // If assertion fails test execution continues
        CHECK(uuid.most > 0);
        CHECK(uuid.least > 0);
    }
}

// BDD style

SCENARIO("UUID creation")
{

    GIVEN("A random UUID ")
    {

        ids::Uuid uuid;
        std::string uuid_str{uuid.to_str()};

        REQUIRE(uuid_str.size() == 36);

        WHEN("get the most and least")
        {
            THEN("should be more than 0")
            {
                CHECK(uuid.most > 0);
                CHECK(uuid.least > 0);
            }
        }
    }
}
----

TIP: Puedes encontrar las instrucciones para construir y ejecutar el proyecto de ejemplo en: https://github.com/carlosvin/uuid-cpp#how-to-build-the-example
