= Choosing a Modern C++ stack
:date: 2017/09/15 20:50:00
:keywords: C++, Unit Testing, Build System, Build Software, Meson, Catch, doctest
:description: My chosen technologies stack for C++ project. It contains an easy to run example defining main project skeleton.
:lang: en
:toc:
:make_link: https://www.gnu.org/software/make/manual/make.html[Make,window=_blank]
:maven: https://maven.apache.org/[Maven,window=_blank]
:scons: https://scons.org/[Scons,window=_blank]
:cmake: https://cmake.org/[CMake,window=_blank]
:meson: https://mesonbuild.com/[Meson,window=_blank]
:gradle: https://gradle.org/[Gradle,window=_blank]
:autotools: https://www.gnu.org/software/automake/manual/html_node/Autotools-Introduction.html[Autotools,window=_blank]
:gnome: https://www.gnome.org/[Gnome,window=_blank]
:ninja: https://ninja-build.org/[Ninja,window=_blank]
:python: https://python.org/[Python,window=_blank]
:catch: https://github.com/philsquared/Catch[Catch,window=_blank]
:doctest: https://github.com/onqtam/doctest[doctest,window=_blank]
:xunit: https://en.wikipedia.org/wiki/XUnit[xUnit,window=_blank]
:bdd: https://en.wikipedia.org/wiki/Behavior-driven_development[BDD,window=_blank]
:uuid: https://en.wikipedia.org/wiki/Universally_unique_identifier[UUID,window=_blank]
:mt19937:  https://www.cplusplus.com/reference/random/mt19937[mt19937,window=_blank]
:benchmarkresults: https://github.com/onqtam/doctest/blob/master/doc/markdown/benchmarks.md[performance results]

I'm starting a new project in C++, but I've run into a pair of questions before start:

. Which build system should I use?
. Which unit testing framework?

== Choosing Build System ({meson})

I have used before {make_link}, {maven}, {scons}, {gradle} and {autotools}, but I have some reasons to try find something else:

{autotools}::
  It is not easy to configure and maintain. There are several configuration files and several configuration steps.
{gradle}::
  C++ feature is still incubating. Not very fast. You can check a similar example project at link:/posts/gradle-cpp/[Build C++ project with Gradle].
{make_link}::
  I don't love the syntax. Files tends to get messy as project grows.
{scons}::
  It is just slower and not as easy to understand than {meson}.
{maven}::
  It is slow and you might end up "_Javatizing_" your C++ project structure.

NOTE: I've listed just things I don't like, those projects have other great features.

=== {cmake} vs {meson}

After discarding previous ones, I'm considering {meson} or {cmake}. Both are fast build systems:

Although {meson} is written in {python}, it generates a {ninja} build project. First time you configure the project you have to run {meson}, but for building or testing you are actually running {ninja}.

{cmake} is also able to generate {ninja} files among other formats, https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html[check CMake generators documentation for more information].

{cmake}::
  It has a big advantage over {meson}, it is mature and widely used in many projects, which means there are many examples and it will fulfill your C++ project building needs.
{meson}::
  It is a young project compared with {cmake}, but it is growing quite fast and it has been adopted in other big projects like link:[Gnome], they have an initiative to https://wiki.gnome.org/Initiatives/GnomeGoals/MesonPorting[port from Autotools to Meson].

*Finally I've chosen* {meson} because syntax is really clear to me, when I read `meson.build` file I can quickly understand what is happening during build process.

.Steps to compile and test a project
[source,bash]
----
$ meson build .  <1>
$ cd build
$ ninja build    <2>
$ ninja test     <3>
----
<1> First time you configure the project
<2> Each time you build it
<3> Each time you run tests

=== Other build systems comparisons
I've found two interesting comparisons about available C++ build systems, they might be a little be biased because those comparisons come from {meson} and {scons}.

* https://bitbucket.org/scons/scons/wiki/SconsVsOtherBuildTools[C++ build systems comparison from Scons].
* https://mesonbuild.com/Simple-comparison.html[C++ build systems comparison from Meson].

== Unit Testing Framework

I have used some {xunit} based libraries like https://github.com/unittest-cpp/unittest-cpp[UnitTest++], https://cpputest.github.io/[CppUTest] or https://github.com/google/googletest[Google Test] which match perfectly with https://github.com/google/googletest/tree/master/googlemock[Google Mock]. If you want a safe bet that fulfills almost of your testing needs I highly recommend https://github.com/google/googletest[Google Test].

But time ago I found a testing framework with some interesting features, {catch}:

* It is just a header file with no external dependencies, so very easy to start (wget + include downloaded file).
* You can use normal unit test style or link:[BDD]-style

If you want to know more about {catch}, I recommend you to give it a try, it is a matter of 2 minutes to have a https://github.com/philsquared/Catch/blob/master/docs/tutorial.md#writing-tests[simple example up and running]. You can also read some interesting articles like https://github.com/philsquared/Catch/blob/master/docs/why-catch.md[Why do we need yet another C++ test framework?] or https://blog.coldflake.com/posts/Testing-C++-with-a-new-Catch/[Testing C++ With A New Catch].

=== {doctest}: A {catch} alternative

There is another testing framework named {doctest}, with same benefits as {catch}, but it promises to be faster and lighter ({benchmarkresults}) than {catch}.

{doctest} is modeled after {catch} and some parts of the code have been taken directly, but there are https://github.com/onqtam/doctest/blob/master/doc/markdown/faq.md#how-is-doctest-different-from-catch[differences].

It hasn't been easy to decide, both are really similar, following you can see differences:

.diff between doctest and catch branches
[source,diff]
----
@@ -1,12 +1,12 @@
-#define CATCH_CONFIG_MAIN // It tells Catch to provide a main() - only do this in one cpp file
+#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

-#include "catch.hpp"
+#include "doctest.h"
#include "Uuid.h"
#include <string>

constexpr int MAX_ITERS = 100;

-TEST_CASE("Uuid", "[uuid]")
+TEST_CASE("Uuid")
{
for (int i = 0; i < MAX_ITERS; i++)
{
@@ -26,7 +26,7 @@ TEST_CASE("Uuid", "[uuid]")

// BDD style

-SCENARIO("UUID creation", "[Uuid]")
+SCENARIO("UUID creation")
{

GIVEN("A random UUID ")
----

I've finally chosen {doctest} because it promises to be faster: {benchmarkresults}.

NOTE: I've created project using both frameworks you can find them in corresponding branches: https://github.com/carlosvin/uuid-cpp/tree/doctest[doctest branch] or https://github.com/carlosvin/uuid-cpp/tree/catch[catch branch].

== Example

I've created an example to illustrate this article: https://github.com/carlosvin/uuid-cpp.

It is a basic implementation of UUID pseudo-random generator based on {mt19937} which is not cryptographically secure.

=== Project output artifacts

When we install the project using {meson} ({ninja}), we will get some artifacts generated and copied in our system.

* Shared library: `libuuid`.
* Header library for developers who want to use the shared library: `include/Uuid.h`.
* Executable `uuidgen` (link:[UUID] generator).
* Test executable (not installed). It tests shared library.

For example, if you execute `ninja install` on Linux, you will get something like:

[source,bash]
----
/usr/local/lib/libuuid.so
/usr/local/include/Uuid.h
/usr/local/bin/uuidgen
----

=== Project structure (https://github.com/carlosvin/uuid-cpp[Fork project])

https://github.com/carlosvin/uuid-cpp/blob/master/meson.build[meson.build]:: Root project file configuration. It defines project properties and subdirectories.

.meson.build
[source,python]
----
project(
    'cpp-meson-example', # project name
    'cpp', # C++ project, e.g: for C project
    version : '1.0.0',
    license : 'MIT',
    default_options : ['cpp_std=c++11']) # compile for C++

# it will be referred from subdir projects
inc = include_directories('include')

# meson will try to find a meson.build file inside following directories
subdir('include')
subdir('src')
subdir('test')
----

https://github.com/carlosvin/uuid-cpp/blob/master/include/[include]::
  meson.build;; Build configuration file for include directory.
  
.include/meson.build
[source,python]
----
# Select header files to be installed
install_headers('Uuid.h')
----

  https://github.com/carlosvin/uuid-cpp/blob/master/include/Uuid.h[Uuid.h];; Header file, it is the library interface definition which will be included from projects using that library

.include/Uuid.h
[source,cpp]
----
namespace ids {

class Uuid {
    private:
    // ...
----

https://github.com/carlosvin/uuid-cpp/blob/master/src[src]::
  
  https://github.com/carlosvin/uuid-cpp/blob/master/src/meson.build[meson.build (src)];; It declares 2 output artifacts, library `libuuid` and executable `uuidgen`. Executable depends on the libary, it will use the libary to generate {uuid}.

.src/meson.build
[source,python]
----
libuuid = shared_library(
    'uuid', <1>
    'Uuid.cpp', <2> 
    include_directories : inc, <3>
    install : true) <4>

uuidgen = executable(
    'uuidgen', <5>
    'main.cpp', <6>
    include_directories : inc, <7>
    link_with : libuuid, <8>
    install : true) <9>
----
<1> library name
<2> source files to be compile
<3> previously declared include directories in root `meson.build`
<4> `libuuid` will be part of project installation
<5> executable name
<6> source files to compile
<7> previously declared include directories in root `meson.build`
<8> linking executable with shared previously declared shared library `libuuid`
<9> `uuidgen` executable be part of project installation

  https://github.com/carlosvin/uuid-cpp/blob/master/src/main.cpp[main.cpp];; Entry point for main executable `uuidgen`.

.src/main.cpp
[source,cpp]
----
#include "Uuid.h"
#include <iostream>

int main()
{
    ids::Uuid uuid;
    std::cout << uuid.to_str() << std::endl;
    return 0;
}
----

  https://github.com/carlosvin/uuid-cpp/blob/master/src/Uuid.cpp[Uuid.cpp];; Implementation of declared class in header file.

.src/Uuid.cpp
[source,cpp]
----
#include "Uuid.h"

Uuid::Uuid()
{ // ...
----

https://github.com/carlosvin/uuid-cpp/blob/master/test/[test]::
  https://github.com/carlosvin/uuid-cpp/blob/master/test/meson.build[meson.build (test)];; File to configure tests build process.
    
.test/meson.build
[source,python]
----
testexe = executable(
    'testexe', <1>
    'uuid_test.cpp', <2>
    include_directories : inc, <3>
    link_with : libuuid) <4>

test('Uuid test', testexe) <5>

test('Uuid test with args and env', testexe, args : ['arg1', 'arg2'], env : ['FOO=bar']) <6>
----
<1> test executable name
<2> tests source files to be compiled
<3> declared include directories in root `meson.build`
<4> link test executable with previously declared shared library `libuuid`
<5> test execution
<6> we can specify other test execution passing arguments or environment variables

  doctest.h;;
    {doctest} library in a single header file. You can try to automate library installation as part of your build process, but I haven not figured out yet a way to do it with {meson}. For now, I have installed it manually:

.Add {doctest} to your project
[source,bash]
----
cd test
wget https://raw.githubusercontent.com/onqtam/doctest/master/doctest/doctest.h
----

  https://github.com/carlosvin/uuid-cpp/blob/master/test/uuid_test.cpp[uuid_test.cpp];;
    Tests implementation.

.test/uuid_test.cpp
[source,cpp]
----
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "doctest.h"
#include "Uuid.h"
#include <string>

constexpr int MAX_ITERS = 100;

TEST_CASE("Uuid")
{
    for (int i = 0; i < MAX_ITERS; i++)
    {
        ids::Uuid uuid;
        std::string uuid_str{uuid.to_str()};

        INFO(uuid_str);

        // If assertion fails test execution is stopped
        REQUIRE(uuid_str.size() == 36);

        // If assertion fails test execution continues
        CHECK(uuid.most > 0);
        CHECK(uuid.least > 0);
    }
}

// BDD style

SCENARIO("UUID creation")
{

    GIVEN("A random UUID ")
    {

        ids::Uuid uuid;
        std::string uuid_str{uuid.to_str()};

        REQUIRE(uuid_str.size() == 36);

        WHEN("get the most and least")
        {
            THEN("should be more than 0")
            {
                CHECK(uuid.most > 0);
                CHECK(uuid.least > 0);
            }
        }
    }
}
----

TIP: You can find how to build and test the example project at: https://github.com/carlosvin/uuid-cpp#how-to-build-the-example
