= Mutex C++
:date: 2014/04/24 17:50:00
:keywords: C++, pthread
:description: Un capa que facilita el uso de los mutex de pthread en C++98 y una mejor solución en C++11
:lang: es
:toc:
:cpp11: https://en.wikipedia.org/wiki/C++11[C++11,window=_blank]
:mutex: https://en.wikipedia.org/wiki/Mutex[Mutex,window=_blank]
:prev_vers: https://clang.llvm.org/cxx_status.html[versiones del compilador anteriores a C++11,window=_blank]
:pthread: https://en.wikipedia.org/wiki/POSIX_Threads[pthread,window=_blank]
:cpp11_mutex: https://en.cppreference.com/w/cpp/thread/mutex[Clase Mutex,window=_blank]
:gist: https://gist.github.com/carlosvin/11257689[Código en Gist,window=_blank]


En {cpp11} se han introducido muchas mejoras que nos ayudan a desarrollar sistemas multi-hilo. Voy a centrarme en los {mutex}.

En las versiones anteriores a {cpp11} una forma de obtener un {mutex} es el que nos proporciona la librería link:[pthread], pero para utilizarlo debíabos inicializarlo y destruirlo al estilo C, en definitiva, tienes que hacer algo más que lock/unlock cada vez que trabajas con un mutex.

{cpp11} nos proporciona una {cpp11_mutex}, que nos abstrae de cosas que no sean lock/unclock. 

[source, cpp]
----
#include <mutex>

std::mutex mtx;

void do_something (int i) {
  mtx.lock();
  // critical section
  mtx.unlock();
}
----

En {cpp11} también puedes utilizar el {mutex} con una https://en.cppreference.com/w/cpp/thread/lock_guard[guarda genérica,window=_blank].

Si sigues trabajando con {prev_vers}, hace tiempo me hice un wrapper que te ayuda a abstraerte del mutex de pthread, lo dejo aquí abajo por si a alguien le resulta útil: [gist].
