= Depurar librería generada con libtool
:date: 2013/02/01 15:30:00
:keywords: C++, Autotools, GNU, Tips and Tricks
:description: Cómo depurar un librería generada con libtool
:lang: es
:toc:
:libtool: https://www.gnu.org/software/libtool/libtool.html[libtool,window=_blank]
:autotools: https://es.wikipedia.org/wiki/GNU_build_system[Autotools,window=_blank]

Cuando vamos a depurar un ejecutable que utiliza una librería generada con {libtool}footnote:[Herramienta que pertenece a la link:[Autotools] usada para crear bibliotecas de software portables.], es posible que nos encontremos con el siguiente error:

[source,bash]
----
$ gdb ./tests-mylib
"tests-mylib": not in executable format: File format not recognized
----

`libmylib.so`:: es una librería dinámica generada con {libtool}.
`tests-mylib`:: es un ejecutable que utiliza la librería mylib.

Para los que estéis pensando que se me ha olvidado poner la opción de compilación `-g`, este error ocurre aunque utilicemos `-g`.

El error es debido a que estamos intentando ejecutar un script generado por {libtool}, es una envoltura sobre el programa real, para facilitar la ejecución de éste footnote:[Más información en https://www.gnu.org/software/libtool/manual/libtool.html#Debugging-executables[documentación de libtool]].

.Para poder depurar nuestro programa de prueba `tests-mylib`
[source,bash]
----
libtool --mode=execute gdb tests-mylib
----
