= Lecciones aprendidas creando una PWA con Create React App
:date: 2019/11/04
:lang: es
:keywords: React, Typescript, CRA, PWA, Create React App, Firebase, Firestore, Svelte, Sapper
:link: https://btapp.netlify.com
:description: Lecciones aprendidas durante la creacion de una PWA: Budget Tracker
:toc:
:React: https://reactjs.org[React,window=_blank]
:Webpack: https://webpack.js.org[Webpack,window=_blank]
:Parcel: https://parceljs.org[Parcel,window=_blank]
:CRA: https://create-react-app.dev[CRA,window=_blank]
:CRALong: https://create-react-app.dev[Create React App,window=_blank]
:PWA: https://developers.google.com/web/progressive-web-apps/[PWA,window=_blank]
:Typescript: https://www.typescriptlang.org[Typescript,window=_blank]
:material-ui: https://material-ui.com[Material UI,window=_blank]
:frappe: https://frappe.io/charts[Frappe charts,window=_blank]
:btapp: https://btapp.netlify.com[Budget Tracker,window=_blank]
:sw: https://developers.google.com/web/fundamentals/primers/service-workers[Service Worker,window=_blank]
:firestore: https://firebase.google.com/docs/firestore[Firestore,window=_blank]
:firebase-auth: https://firebase.google.com/docs/auth[Firebase Authentication,window=_blank]
:ww: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers[Web Workers,window=_blank]
:indexeddb: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API[IndexedDB,window=_blank]
:firebase: https://firebase.google.com/[Firebase,window=_blank]


Empezé trabajando con {React} hace unos años, siempre he comenzado los proyectos desde cero, sin utilizar ninguna plantilla o generador de proyectos. En lo que ser refiere a los empaquetadores, normalmente utilizo {Webpack} en el trabajo o https://parceljs.org[Parcel] en proyectos personales.

Hace unos meses, quería comenzar un proyecto personal para hacer un seguimiento de mis gastos durante mi año sabático, {btapp} lo llamé. Llevaba un poco de prisa, porque en ese momento llevaba ya unos 4 meses viajando y quería centrarme cuanto antes en implementar la funcionalidad principal y tener algo funcionando cuanto antes, un https://en.wikipedia.org/wiki/Minimum_viable_product[MVP] (minimum viable product), estaba en la situación perfecta para probar {CRALong} o {CRA}.

NOTE: {CRA} te permite crear una {PWA} en {React} lista para producción en un momento, lo que es impresionante. Solo tienes el esqueleto de la aplicación, tampoco hace milagros, el resto lo tienes que programar tú. {CRA} se encarga de la gestión de dependencias de desarrollo y configuración de el empaquetador, {Webpack} en este caso.


Como decía antes, quería implementar la lógica del programa cuanto antes, así que junto con la utilización de {CRA}, tambien tomé otras decisiones y atajos, condicionados por la necesidad de acelerar el proceso de desarrollo, hablaré sobre todas estas decisiones a lo largo de este artículo.

== Tecnologías escogidas para crear {btapp}

* {CRA}
* {React}
* {Typescript}
* {material-ui}
* [line-through]#https://formidable.com/open-source/victory[Victory]# {frappe}
* {firestore}
* {firebase-auth}

Estoy bastante contento con el resultado, pero teniendo en cuenta lo aprendido durante el desarrollo de este proyecto, *en el futuro y con el tiempo suficiente, lo más seguro es que no volviese a elegir este mismo conjunto*.

Puedes evaluar el resultado de usar este conjunto de tecnologías abriendo {btapp}.

A continuación, haré un análisis más detallado de algunos de los beneficios e inconvenientes de las decisiones y atajos que tomé durante el desarrollo de {btapp}.

== Create React Application: {CRA}

{CRALong} no ofrece soporte para {ww} ni permite modificar la implementación del {sw} sin https://stackoverflow.com/questions/49737652/what-does-eject-do-in-create-react-app[expulsar (eject)] la configuración.

NOTE: ¿Qué significa explusar o "`eject`" en {CRA}? Básicamente es que la configuración de tu proyecto ya no está gestionada por {CRA}, por lo que tienes que te tienes que hacer cargo de ella, mantener las dependencias y configuración de todos los aspectos de tu proyecto como las pruebas, el análisis estático de código, la configuración de Babel y la lista continúa.

=== Service worker

Es posible que necesites modificar el comportamiento de tu {sw} para enviar/recibir https://developer.mozilla.org/en-US/docs/Web/API/Client/postMessage[mensajes post], para realizar https://wicg.github.io/BackgroundSync/spec/[sincronización en segundo plano] o https://developer.mozilla.org/en/docs/Web/API/notification[mostrar notificaciones web]. En ese caso tendrá que https://stackoverflow.com/questions/49737652/what-does-eject-do-in-create-react-app[extraer tu proyecto (eject)] y mantener la configuración por tí misma/mismo, lo cual puede suponer algún que otro dolor de cabeza innecesario.

Hay https://www.freecodecamp.org/news/how-to-customize-service-workers-with-create-react-app-4424dda6210c/[otras opciones para evitar extraer CRA], pero son un poco complicadas para mi gusto.

=== Web worker

Cuando necesitas ejecutar algún procesamiento sin bloquear el hilo principal, puedes enviarlo a un {ww}, lo malo es que tampoco están soportados por {CRA}. El {ww} también puebe comunicarse con el hilo principal usando https://developer.mozilla.org/en-US/docs/Web/API/Client/postMessage[mensajes post] y también puede mostrar https://medium.com/young-coder/a-simple-introduction-to-web-workers-in-javascript-b3504f9d9d1c[notificaciones web].

También hay https://medium.com/@danilog1905/how-to-use-web-workers-with-react-create-app-and-not-ejecting-in-the-attempt-3718d2a1166b[otras opciones para evitar extraer la configuración de CRA], pero requieren un poco de trabajo extra.

=== Webpack

{Webpack} es el empaquetador utilizado por {CRA}. Cuando utilizas {CRA}, no necesitas saber mucho sobre éste, pero cuando tienes que https://stackoverflow.com/questions/49737652/what-does-eject-do-in-create-react-app[extraer tu proyecto (eject)], entonces tendrás que lidiar con el https://webpack.js.org/configuration/[archivo de configuracion de Webpack].

== Firebase

{btapp} permite sincronizar tus presupuestos entre distintos dispositivos, por lo que esta aplicación necesita un lado https://en.wikipedia.org/wiki/Front_and_back_ends[backend] para gestionar la autenticación y guardar/leer los datos. Consideré dos opciones: {firebase} implementar una API https://en.wikipedia.org/wiki/Representational_state_transfer[REST].

Elegí {firebase} porque no hay que implementar nada en el lado servidor, sólo hay que configurar los https://support.google.com/firebase/answer/6400716?hl=en[métodos de autenticación] y las https://firebase.google.com/docs/firestore/security/get-started[reglas de seguridad] en {firestore}.

Pero {firebase} viene con algunos inconvenientes que debes conocer antes de elegirlo.

=== Inconvenientes

==== Tamaño de la librería

Me sorprendió mucho la primera vez que analicé el tamaño de la aplicación {btapp} justo después de integrarla con {firebase}, *¡creció un 39%!*.

* 27% por la librería {firestore}.
* 12% por la librería {firebase-auth}.

Afortunadamente {btapp} está implementado particionando el código (https://reactjs.org/docs/code-splitting.html[code-splitting]), lo que permite cargar solo las partes necesarias de la aplicación, así que, la experiencia de usuario no se vió gravemente afectada. Lo malo es que el usuario, en algún momento, tendrá que descargar ese *39% extra* (*539KB*).

==== No realmente primero offline

IMPORTANT: Esto no es relevante, si para tu caso de uso no tienes que vincular los datos al usuario.

{firestore} necesita un usuario identificado para realizar lecturas y escrituras, pero https://firebase.google.com/docs/auth/web/anonymous-auth[permite trabajar con usuarios anónimos], esta característica es muy interesante si no quieres forzar al usuario a identificarse para utilizar la aplicación.

Otra característica muy útil es que https://firebase.google.com/docs/firestore/manage-data/enable-offline[soporta modo offline], lo que permite guardar y leer información cuando no hay conexión a Internet.

Los usuarios anónimos junto con el modo offline, casi permiten tener una aplicación que funcione completamente offline.

Entonces… ¿Qué es esto de <<No realmente primero offline>>? Esto significa, que la primera vez que la aplicación es abierta, {firebase} necesita identificar al usuario, para ello, en este momento, el dispositivo del usuario debe estar conectado a Internet, en este caso, *debes considerar el siguiente escenario*:

. La {PWA} está instalada en tu dispositivo.
. El usuario no está identificado.
. El dipositivo no tiene acceso a Internet.
. El usuario abre la {PWA} e intenta guardar o leer datos.
. *La información no se podrá guardar correctamente*, porque se desconoce el usuario al que pertenece esta información y tampoco se puede vincular a un usuario anónimo, porque se necesita conexión para crearlo.

Esto no es un problema importane, la aplicación funcionará perfectamente en la mayoría de casos. Si, aún así quieres resolver este caso, a continuación explicaré cómo lo he solucionado en {btapp}.

===== Convertir Budget Tracker como offline first

Antes de nada, me gustaría remarcar que esto *podría no ser necesario para tu caso de uso*, porque sólo ocurrirá la primera vez que arranque la aplicación y no tenga conexión a Internet. En el caso de {btapp} me aseguré de que funcionase en todo momento en modo offline porque traía otros beneficios que más adelante enumeraré.

====== Detalles de implementación

* Crear dos capas de persistencia: Local ({indexeddb}) y Remota ({firestore}).
* Guardar los datos siempre de forma local, independientemente de si el usuario está identificado o no.
* Si hay un usuario que ya está identificado, después de actuar sobre el almacenamiento local, realizar exactamente la misma acción sobre la capa de almacenamiento remoto {firestore} de forma asíncrona.

====== Beneficios

* Si el usuario no se ha identificado, {btapp} no cargará la librería cliente de {firestore}. Como ya comenté antes, ésta supone un 27% del tamaño de la aplicación.
* Las escrituras y lecturas son algo más rápidas, porque el almacenamiento primario es local.
* *Aclaración*: La interación con {firestore} también es rápida, porque también almacena la información localmente, pero también hace unas cuantas cosas más que simplemente interactuar con {indexeddb} y necesitas un usuario identificado.

Puedes encontrar un https://github.com/carlosvin/budget-tracker/blob/master/doc/preformance.md#desktop-slow-clear-storage-0-budgets-1[informe más detallado sobre el rendimiento], donde se analizan tres escenarios diferentes:

. {firestore} como única capa de persistencia.
. Dos capas de persistencia, una local ({indexeddb}) y otra remota ({firestore}),
. Igual que la anterior, pero se interactúa con {firestore} desde un service worker.

En general, se obtienen mejores resultados con la opción 2.

==== Modelo de Datos

La API de {firestore} es fácil e intuitiva, me encanta, pero no asumas que tendrá todas las características que ofrecen otras bases de datos documentales o relacionales (SQL).

Comprueba que las https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/datamodel.html[limitaciones de Firestore] encajan con tu modelo de datos, o si no es demasiado tarde, diseña tu modelo de datos siguiendo la guía de https://cloud.google.com/firestore/docs/best-practices[buenas prácticas de Firestore].

=== Alternativas a Firebase

A parte de implementar una API https://en.wikipedia.org/wiki/Representational_state_transfer[REST] para tu aplicación, hay otros servicios similares a {firebase} con un tamaño menor de la librería cliente y otras características que pueden adaptarse mejor a tus necesidades.

Algunas alternativas a considerar:

* Basado en http://couchdb.apache.org/[Apache CouchDB]: https://pouchdb.com[PouchDB], https://en.wikipedia.org/wiki/Cloudant[Cloudant].
* Basado en https://parseplatform.org/[Parse server]: https://www.back4app.com[back4apps].

== Librería de componentes de interfaz de usuario: {material-ui}

Elegí {material-ui}.

[quote, {material-ui}, citando su sitio web]
Componentes de React para un desarrollo web más rápido y sencillo. Construya su propio sistema de diseño, o empiece con Material Design.

Hay dos razones principales por las que elegí una libreria de componentes UI:

* Es laborioso crear tus propios componentes de interfaz de usuario que sean accesibles, que se adapten correctamente a distintos dispositivos y con un diseño estéticamente correcto.
* {material-ui} tiene un conjunto de iconos SVG, https://material-ui.com/components/material-icons/[Material Icons]. Esto me venía muy bien para {btapp}, porque permite crear categorías para gastos y asignar un icono a éstas categorías.

Hay algunos *problemas*, no muy importantes en mi opinión, quizá el que me resulta más molesto es el primero:

* https://jestjs.io/docs/en/snapshot-testing[Jest Snapshots] + {material-ui}: Los https://jestjs.io/docs/en/snapshot-testing[Jest Snapshots] guardan también las classes CSS utilizadas por {material-ui}, pero el orden de estas clases podría no ser determinístico, por lo que el resultado de una prueba podría ser satisfactorio en tu portátil, pero podría fallar en cualquier otro sitio, como en la máquina donde se ejecuta el servidor de integración continua (https://en.wikipedia.org/wiki/Continuous_integration[CI]). Están trabajando en solucionar https://github.com/mui-org/material-ui/issues/14357[este problema, más información en Github].
* Rendimiento: Hay algunos https://github.com/mui-org/material-ui/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+performance[problemas de rendimiento en Github]. A lo largo de los últimos meses, mientras he utilizado esta librería, puedo decir que el equipo de desarrollo está trabajando duro en mejorar esta librería y supongo que los solucionarán pronto.
* Las librerías de componentes de interfaz de usuario son complejas y hacen muchas cosas, por ello la mayoría son bastante pesadas. https://bundlephobia.com/result?p=@material-ui/core@4.5.2[El tamaño de Material UI reducido son 304.2kB]. Puedes encontrar https://material-ui.com/guides/minimizing-bundle-size[recomendaciones para reducir el tamaño de tu aplicación al utilizar Material UI en su documentación].

== Librerías de gráficas

Muchas de las librerías que he encontrado son muy potentes y completas, pero también ocupan bastante, entre otras cosas porque dependen en otras librerías como https://d3js.org/[D3].

Inicialmente elegí https://formidable.com/open-source/victory[Victory], pero me dí cuenta de que sólamente necesitaba gráficos para mostrar porcentajes y series temporales. Otro hecho relevante es que https://formidable.com/open-source/victory[Victory] tiene un https://bundlephobia.com/result?p=victory@33.1.2[tamaño de 468KB] y yo no estaba utilizando la mayor parte de ese código.

Después de una búsqueda rápida en Internet, encontré otras alternativas mucho más ligeras y más que suficientes para mis necesidades:

* {frappe}: https://bundlephobia.com/result?p=frappe-charts@1.3.0[63KB].
* https://gionkunz.github.io/chartist-js[Chartist]: https://bundlephobia.com/result?p=chartist@0.11.4[39KB].

Probé las dos y me encantaron las dos, finalmente elegí {frappe} porque su esquema de colores se ajusta mejor al tema de {btapp}.

Ambas librerías traen más tipos de gráficos que los de ejes de coordenadas XY o gráfico de barras. Echa un vistazo a sus sitios web si quieres saber un poco más.

== Conclusión

Intentaré llegar a una conclusión algo mejor que _"Depende"_, _"Tu caso de uso te dirá"_, etc. Dicho esto, depende de lo que necesites :p.

Ya en serio, voy a listar las conclusiones en la forma _"No utilices … si …"_.

=== No utilices CRA si

* Si tienes que modificar el {sw} para realizar https://developers.google.com/web/updates/2015/12/background-sync[Background sync] o para https://developer.mozilla.org/en/docs/Web/API/notification[mostrar notificaciones web].
* Si tienes que utilizar {ww}.

=== No utilices Firestore si

* Si esperas que tu aplicación sea utilizada por muchos usuarios y no tienes idea de la cantidad de lecturas y escrituras que necesitas por usuario, te podrías llevar un sorpresa en la factura que te pase Google. {firestore} escala perfectamente, pero tu presupuesto quizá no.
* Si el tamaño de tu aplicación web es algo crítico. Recuerda que el tamaño de tu aplicación, si se trata de una {PWA}, no es tan importante, porque los archivos normalmente estará cacheados para que la aplicación pueda abrirse offline.

=== No elijas la mejor librería de gráficos

Antes de nada, analiza qué tipos de gráficos necesitas. En muchos casos, es más que suficiente con gráficos XY, de tarta o de barras. Puedes fácilmente reducir el tamaño de tu aplicación utilizando librerías como {frappe} or https://gionkunz.github.io/chartist-js[Chartist]

TIP: Simplemente asegúrate de que tus requisitos son compatibles con las limitaciones o problemas de los que acabo de hablar. Si no estás segura o seguro, las <<Tecnologías escogidas para crear {btapp}>> debería ser suficiente para cualquier {PWA}.

== ¿Y ahora qué?

Mi próxima apuesta para el lado https://en.wikipedia.org/wiki/Front_and_back_ends[frontend] es {Svelte}/{Sapper}. Es un proyecto prometedor que ha cambiado el paradigma de framework en tiempo de ejecución a framework en tiempo de compilación. Hasta ahora, los resultados en proyectos pequeños son impresionantes, sobre todo en lo relacionado con el tamaño de la aplicación generada y con lo fácil e intuitivo que resulta el desarrollo con {Svelte}.

He creado una sencilla {PWA} para https://currency-loss.netlify.com[calcular el dinero que pierdes] cuando vas a una casa de cambio: https://currency-loss.netlify.com[currency-loss.netlify.com].

Terminé esta aplicación en pocas horas gracias a {Svelte}.
