= Create SPA: React + Typescript + Parcel
:date: 2019/01/01 13:30:02
:lang: en
:modified: 2019/07/10 13:30:02
:keywords: React, Typescript, Parcel, SPA
:link: https://github.com/carlosvin/react-typescript-parcel-template
:description: Example project how to create a Single Page Application with React, Typescript and Parcel.
:toc:
:parcel: https://parceljs.org[Parcel,window=_blank]
:react: https://reactjs.org[React,window=_blank]
:typescript: https://www.typescriptlang.org/[Typescript,window=_blank]
:webpack: https://webpack.js.org/[Webpack,window=_blank]
:cra: https://facebook.github.io/create-react-app/[create-react-app,window=_blank]

I was about to start yet another personal project, it consists of a SPA (Single Page Application) for a travel journal.

Some time ago I tried {parcel}, I really loved how simple it was to create a simple project from scratch, using {typescript} + {react} stack. I’ve decided to create this template or base project, so next time I want to create a new SPA with my favorite frontend stack, I will only have to:

[source,bash]
----
git clone https://github.com/carlosvin/react-typescript-parcel-template.git
----

== Read this before: Parcel is not as mature as Webpack

If you want to create a production ready React application, use {webpack} or better {cra} which bring everything you need to develop a https://developers.google.com/web/progressive-web-apps/[PWA] with React and Typescript. Following you can find an example of an app I am developing using {cra}: https://github.com/carlosvin/budget-tracker.

Parcel is a package bundler under development, not as mature as webpack. There are no go errors for me, at least in regards to Typescript support, see this https://github.com/parcel-bundler/parcel/issues/1378[issue in github #1378].

I still think it is a promising project, bringing more simplicity and speed to JS bundlers world, I will give it a try again for serious projects when Parcel 2 is ready, check https://github.com/parcel-bundler/parcel/projects/5[Parcel 2 development status].

== Quick start

=== Development server

[source,bash]
----
git clone https://github.com/carlosvin/react-typescript-parcel-template.git
cd react-typescript-parcel-template
yarn install
yarn start
----

Last `yarn start` command will: 

* start a development server at http://localhost:1234 with https://en.parceljs.org/hmr.html[hot module replacement] 
* build automatically development javascript files with source maps

TIP: Each time you save a file, you will see automatically the result at `http://localhost:1234` without refreshing the page

=== Build production bundle

[source,bash]
----
yarn build
----

https://en.parceljs.org/production.html#optimisations[Parcel’s default optimizations] will be applied to generated files.

Files are saved at `+dist+` folder. Inside `+dist+` folder there is also a file with information about bundle content sizes: `dist/report.html`.

== Step by step project creation

In this section I will describe how I created this project.

Firstly, create `package.json` with https://yarnpkg.com/lang/en/docs/cli/init/[yarn init] command.

[source,bash]
----
yarn init
----

=== Add required dependencies

Add {react} dependencies.

[source,bash]
----
yarn add @types/react @types/react-dom react react-dom
----

Previous command modifies `package.json` file adding `dependencies` section and will also install React packages in `node_modules` folder.

[source,json]
----
{
  "name": "project_name",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@types/react": "^16.7.18",
    "@types/react-dom": "^16.0.11",
    "react": "^16.7.0",
    "react-dom": "^16.7.0"
  }
}
----

Add {typescript} compiler as development dependency.

[source,bash]
----
yarn add --dev typescript
----

We also need https://parceljs.org/[Parcel bundler].

[source,bash]
----
yarn add --dev parcel-bundler
----

I’ve added a non-required dependency, it is a plugin to generate a report of generated bundle contents (the parcel version of https://github.com/webpack-contrib/webpack-bundle-analyzer[webpack-bundle-analyzer].

[source,bash]
----
yarn add --dev parcel-plugin-bundle-visualiser
----

=== Create application source code

First we create the React application in `src/index.tsx` file.

[source,tsx]
----
import * as React from "react";
import * as ReactDOM from "react-dom";

class App extends React.PureComponent {
    render() {
        return <h1>Hello world!</h1>;
    }
}

ReactDOM.render(
    <App />,
    document.getElementById("app")
);
----

Parcel can take `index.html` file as entry file and it figures out how to build the application, so let’s create `src/index.html` as follows:

[source,html]
----
<html>
  <body>
    <div id="app"></div>
    <script src="./index.tsx"></script>
  </body>
</html>
----

We need `div` tag for React to inject the DOM elements. The `script` declaration is used by Parcel to find entry point to build.

=== Add commands build the project

I’ve added the commands:

* `build`: Check _"Build production bundle"_ section.
* `start`: Check _"Development server"_ section.

[source,json]
----
    "scripts": {
        "start": "parcel src/index.html",
        "build": "parcel build src/index.html"
    }
----

Then to it is really easy to:

* run development server: `yarn start`
* generate a production bundle: `yarn build`

There is another approach described in https://en.parceljs.org/getting_started.html[Parcel documentation] that consists of installing Parcel globally.

I’ve opted for more isolated approach that affects only project you are working on, you just install Parcel as `devDependency`. There is a tiny drawback, you can’t just run `parcel index.html`, because it is not installed in your system, but in `node_modules`.

There is a simple way to run any binary installed in `node_modules`, you can just run `npx parcel index.html`.

I like more to define build steps in `+package.json+` file, so you can have well defined commands more suited to build your project. You can also use these commands as documentation how to build your project.

=== Configure Typescript (optional)

.Create a `tsconfig.json` file
[source,json]
----
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es5",
        "jsx": "react"
    }
}
----

With this configuration, Typescript compiler will:

* Generate files in `dist` folder.
* Generate https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map[source maps].
* Will not allow to declare `+any+` type, for example following declaration is not allowed: `+const elements: any;+`
* Generated module code will be https://requirejs.org/docs/commonjs.html[CommonJs].
* Generated code will be https://es.wikipedia.org/wiki/ECMAScript[ECMAScript] 5 compliant.
* Support https://www.typescriptlang.org/docs/handbook/jsx.html[JSX] in `.tsx` files.

== Full source code

You can find full example at: https://github.com/carlosvin/react-typescript-parcel-template.

Or you can directly download the source code:

* https://github.com/carlosvin/react-typescript-parcel-template/archive/1.0.zip[zip]
* https://github.com/carlosvin/react-typescript-parcel-template/archive/1.0.tar.gz[tar.gz]
