= This is Sapper!
:date: 2020-04-19
:lang: en
:description: This blog has been migrated from Nikola to Sapper. Following the reasons why, some thoughts and performance results.
:nikola: https://getnikola.com[Nikola,window='_blank']
:rst: https://en.wikipedia.org/wiki/ReStructuredText[reStructuredText,window='_blank']
:md: https://en.wikipedia.org/wiki/Markdown[Markdown,window='_blank']
:asciidoc: https://asciidoctor.org/[Asciidoctor,window='_blank']
:python: https://python.org[Python,window='_blank']
:lighthouse: https://developers.google.com/web/tools/lighthouse[Lighthouse audits,window='_blank']
:js: https://en.wikipedia.org/wiki/JavaScript[JavaScript,window='_blank']
:html: https://en.wikipedia.org/wiki/HTML[HTML,window='_blank']


This blog was powered by {nikola} since 2014, which is not bad at all. It really did the job, it has out-of-the-box features that I needed:

- Simple multi-lang support.
- {rst} which I prefer over {md}. 
- It was developed in {python}, a programming language that I know and I enjoy.

But I was facing some issues which annoyed me for quite some time, some of the I am pretty sure I could have overcame.

- My config file got bloat.
- For me was not easy to modify or create templates, neither to find templates I liked.
- Site performance was not awesome, my last {lighthouse} were between 70 to 80, depending on the section. Except SEO section, which was 96.

== Asciidoctor
I don't have strong feelings about using {asciidoc} or {rst}. I am comfortable with both of them, there is more support for {asciidoc} in other languages, like {js}. So basically I switch to {asciidoc} because I didn't find a {js} library able to properly convert {rst} to {html}.

== Syntax highlinghting

== To improve