= Mutex C++
2014/04/24 17:50:00
:keywords: C++, pthread

:toc:

[abstract]
== Abstract
Un capa que facilita el uso de los mutex de pthread en C++98 y una mejor solución en C++11_

En link:[C++11] se han introducido muchas mejoras que nos ayudan a desarrollar sistemas multi-hilo. Voy a centrarme en los link:[mutex].

En las versiones anteriores a link:[C++11] una forma de obtener un link:[mutex] es el que nos proporciona la librería link:[pthread], pero para utilizarlo debíabos inicializarlo y destruirlo en estilo link:[C], en definitiva, tienes que hacer algo más que lock/unlock cada vez que trabajas con un mutex.

link:[C++11] nos proporciona una link:[clase mutex], que nos abstrae de cosas que no son lock/unclock. Os recomiendo que echéis un vistazo y veáis lo limpio que queda el código: link:[Clase mutex de C++11].

Si sigues trabajando con link:[versiones de compiladores previos a C++11], hace tiempo me hice un wrapper que te ayuda a abstraerte del mutex de pthread, lo dejo aquí abajo por si a alguien le resulta útil.

Abajo está un link:[Gist del Código], he vuelto a escribir el código de cabeza y puede ser que haya algún error, lo revisaré, pero lo importante es la idea de hacer una clase que envuelva la inicialización del mutex de pthread.

https://gist.github.com/carlosvin/11257689

_mutex::
  https://es.wikipedia.org/wiki/Exclusi%C3%B3n_mutua_(inform%C3%A1tica)

_C::
  https://es.wikipedia.org/wiki/C_(lenguaje_de_programaci%C3%B3n)

_pthread::
  https://en.wikipedia.org/wiki/POSIX_Threads
