= First post with Nikola
2014/03/27 13:30:02
:toc:

[abstract]
== Abstract
My first post with Nikola

I guess that most people come from dynamic content management systems based on:

* send data from browser to server
* process the received data, then it stores the info into a database (or files)
* the server generate dynamically an answer that is sent to the browser as HTML
** the answer is usually built reading info from a database or files.

This process is managed by a software installed on server, this is our content management system.

Now I've changed the paradigm to "static web site generator", specifically I'm going to use link:#nikola[Nikola], although this time, I'm not going to install on a remote server.

In a next post I'll tell you how I've automated the publication process using link:[Github]footnote:[link:[Github] hosts the generated site, the static files (html, css, images, js).] and link:[Travis]footnote:[link:[Travis] is a continuous integration software (like link:[Jenkins]). I use it to automate the site deployment: download the files when they change from link:[Github], re-generate and re-publish the static files.].

Path to link:#nikola[Nikola]

== link:#phpnuke[PhpNuke]

My first content management system, yes it still exists. It based on PHP+MySQL, multi-lang, user management, user groups, theming, plugins, etc.

== My Own Content Management System

It wasn't a full link:#CMS[[CMS]], because actually it was a blogging system. I can publish posts dynamically, it was made with PHP and MySQL. It was useful to:

* Publish posts (with several problems).
* I realized that a developer needs a designer.
* I don't like the link:[PHP] syntax.
* I began to understand the importance of link:#DRY[[DRY]].

=== link:#drupal[Drupal]

A full link:#CMS[[CMS]], I liked it until things began to "break" (Maybe I broke some of them). But link:#drupal[Drupal] has everything you expect from a link:#CMS[[CMS]] and more.

=== link:#wordpress[Wordpress]

I don't know if it is better or worse than link:#drupal[Drupal], there are many discussions on the Internet, but I can tell link:#wordpress[Wordpress] is more usable and easier to update than link:#drupal[Drupal].

=== link:#cmsdj[CMSdj]

It is my second attempt to create my own link:#CMS[[CMS]]. I had an idea in my mind about how to make the core design (the data model), I still believe in that design. I had also discovered link:[Django], I liked this framework developed in link:[Python], who can resist creating their own link:#CMS[[CMS]]? link:#cmsdj[CMSdj] is in link:[Bitbucket] and is working, it has its internal search engine, theming, comment system, voting system,HTML5_ + link:[CSS3] views, but:

* I didn't have enough time to develop it, two hours per week at most.
* I still needed a designer.

So, I declared the project link:#cmsdj[CMSdj] dead out of boredom, although it was supporting my old blog, when I went to write something, I saw my unfinished project, I didn't like it, so I decided to close it and begin a new one.

=== link:#nikola[Nikola]

I wanted a static website generator because they are trendy. I tried link:[Jekyll] because it's the most famous, but I prefer one written in link:[Python]. So, after a quick search I had three finalists: link:#nikola[Nikola], link:[Mynt] and link:[Pelican]. I chose link:#nikola[Nikola] because I discarded the others: * link:[Pelican] throws some multi-lang problems with the categories. I didn't want to spend time researching about how to fix them. * I love the simplicity of link:[Mynt], but you have to create your own themes.

_PhpNuke::
  https://www.phpnuke.org/
_Drupal::
  https://drupal.org/
_Wordpress::
  https://wordpress.org/
_PHP::
  https://www.php.net/
_Python::
  https://www.python.org
_Django::
  https://www.djangoproject.com/
_CMSdj::
  https://bitbucket.org/carlosvin/cmsdj
_Bitbucket::
  https://bitbucket.org
_Nikola::
  https://getnikola.com/
_Jekyll::
  https://jekyllrb.com/
_Pelican::
  https://blog.getpelican.com/
_Mynt::
  https://mynt.mirroredwhite.com/
_Travis::
  https://travis-ci.org/
_Github::
  https://www.github.com
_CSS3::
  https://www.w3.org/Style/CSS/current-work
_HTML5::
  https://www.w3.org/html/
_Jenkins::
  https://jenkins-ci.org/

[[citations]]
[#CMS .citation-label]#CMS#::
  Content Management System
[#DRY .citation-label]#DRY#::
  Don't Repeat Yourself, ´DRY in wiki´_
