= Primer Post utilizando Nikola
2014/03/27 13:30:02
:keywords: Python, Static Sites

:toc:

[abstract]
== Abstract
Cómo he llegado hasta Nikola

Supongo que, como la mayoría, vengo del concepto de software de gestión de blogs o gestores de contenidos dinámicos, basados en:

* enviar información desde un navegador a un servidor
* procesar y almacenar la información en una base de datos o en ficheros
* el servidor genera una respuesta dinámicamente que se envía al navegador en forma de HTML
** para generar esta respuesta se suele leer de la base de datos o de los ficheros

De todo este proceso se encarga un software instalado en el servidor, nuestro gestor de contenidos.

Ahora he cambiado al paradigma de "generador de sitios web estáticos", en concreto voy a utilizar link:#nikola[Nikola], aunque esta vez no lo voy a instalar en ningún servidor. En otro post os contaré cómo he montado esto con link:[Github]footnote:[En link:[Github] alojo el sitio generado, toda la parte estática (las páginas en HTML, imágenes, etc.)] y link:[Travis]footnote:[link:[Travis] es un software the integración contínua (como link:[Jenkins]), yo lo utilizo para automatizar el despliegue del sitio, esto es, para descargar el sitio cada vez que lo cambie en link:[Github], volver a generarlo y publicarlo otra vez.].

Mi camino para llegar hasta los generadores de sitios web estáticos ha pasado por las etapas que os cuento abajo (me he saltado alguna menos importante).

Camino hasta link:#nikola[Nikola]

== link:#phpnuke[PhpNuke]

Sí, sigue existiendo. Aquí entramos un gestor de contenido basado PHP+MySQL, multi-idioma, gestión de usuarios, grupos de usuarios, ampliable con temas, plugins, etc.

== Mi propio gestor de contenidos

Que no era tal, porque se quedó en un blog en el que podía publicar contenidos dinámicamente, también hecho en PHP y MySQL. Me sirvió para:

* Publicar posts con problemas.
* Darme cuenta de que un programador necesita a un diseñador.
* link:[PHP] a nivel sintáctico, es feo (cuestión de gustos).
* Empezar a entender la importancia de link:[DRY]footnote:[Don't Repeat Yourself (En español, "no te repitas")].

== link:#drupal[Drupal]

Un gestor de contenidos muy completo, que me gustó mucho, hasta que se empezaron a "romper" cosas (comparto culpa con link:#drupal[Drupal]) y me cansé. Pero quiero remarcar que tiene todo lo que yo podía esperar de un gestor de contenidos y más.

== link:#wordpress[Wordpress]

Ya no voy a entrar en si es mejor o peor que link:#drupal[Drupal], que de eso hay mucho por Internet. Simplemente es mucho más usable y fácil de actualizar.

== link:#cmsdj[CMSdj]

Mi segundo intento de creación de mi propio gestor de contenidos. Tenía una idea en la cabeza, de cómo debería ser un diseño del modelo de un gestor de contenidos, todavía la tengo. Y recientemente había descubierto link:[Django], un framework que me encantó hecho con un lenguaje que me encanta, link:[Python], ¿quién se puede resistir ahora a crear su propio CMSfootnote:[Content Management System ("Sistema de gestión de contenidos")]? link:#cmsdj[CMSdj] está por ahí en link:[Bitbucket] y funciona, tiene su propio buscador, gestión de templates, sistema de comentarios, sistema de votación, acercamiento a link:[HTML5] + link:[CSS3] y algunas cosillas más, pero:

* Ya no sacaba tiempo para desarrollar, un par de horas a la semana, como mucho, y gastaba una hora en recordar por donde iba.
* Seguía necesitando un diseñador.

Así que declaré este proyecto muerto por aburrimiento, aunque seguí utilizándolo para publicar mis cosillas, pero cada vez que iba a escribir algo en mi blog y veía todo a medio hacer, me ponía malo, así que decidí cerrar y empezar de nuevo.

== link:#nikola[Nikola]

Tengo que decir que quería un generador de sitios estáticos, porque están de moda y toda la gente escribe sobre sus bondades y me convencieron. Probé link:[Jekyll] para que no me lo contaran, que es el más famoso. Pero prefería uno hecho en link:[Python] por si quería meter mano alguna vez. Así que después de buscar un poco, me quedé entre link:#nikola[Nikola], link:[Mynt] y link:[Pelican]. Me quedé con link:#nikola[Nikola] por descarte: * link:[Pelican] me dió algunos problemas en la utilización de varios idiomas y en las categorías, aunque de primeras fue el que más me convenció. De hecho, es posible que esos problemas los crease yo, pero no quería gastar mucho tiempo en investigar. * link:[Mynt] me encantó por su sencillez, aunque tienes que hacerte tus propios templates y no quiero darme cuenta otra vez de lo que necesito a un diseñador.

_DRY::
  https://en.wikipedia.org/wiki/Don't_repeat_yourself
_PhpNuke::
  https://www.phpnuke.org/
_Drupal::
  https://drupal.org/
_Wordpress::
  https://wordpress.org/
_PHP::
  https://www.php.net/
_Python::
  https://www.python.org
_Django::
  https://www.djangoproject.com/
_CMSdj::
  https://bitbucket.org/carlosvin/cmsdj
_Bitbucket::
  https://bitbucket.org
_Nikola::
  https://getnikola.com/
_Jekyll::
  https://jekyllrb.com/
_Pelican::
  https://blog.getpelican.com/
_Mynt::
  https://mynt.mirroredwhite.com/
_Travis::
  https://travis-ci.org/
_Github::
  https://www.github.com
_CSS3::
  https://www.w3.org/Style/CSS/current-work
_HTML5::
  https://www.w3.org/html/
_Jenkins::
  https://jenkins-ci.org/
