= Comparación frameworks REST para RUST
2016/03/01 20:40:00
:keywords: Frameworks, Rustlang, Programming Languages, REST

:toc:

[abstract]
== Abstract
Comparación entre frameworks REST para RUST

Estoy empezando a hacer mis primeros pinitos con link:[Rust], es un lenguage de programación que promete ser tan rápido como link:[C/C++], pero más seguro en cuanto a la gestión de memoria ser refiere. Básicamente, no permite al programador hacer "cosas malas" con la memoria como: olvidarse de liberar la memoria que no se va a utilizar o liberar memoria que no es tuya. En estos casos, link:[Rust] simplemente no compilará.

Para aprender he pensado en hacer algún pequeño proyecto, tengo algunas ideas, pero todas pasan por ofrecer una link:[API] link:[REST], así que me he puesto a buscar frameworks que me faciliten esta tarea y me he llevado una grata sorpresa al encontrar una muy https://github.com/flosse/rust-web-framework-comparison[buena comparativa con el estado de los frameworks REST para Rust], a continuación os dejo el enlace:

https://github.com/flosse/rust-web-framework-comparison

_Rust::
  https://www.rust-lang.org/

_REST::
  https://en.wikipedia.org/wiki/Representational_state_transfer
_API::
  https://en.wikipedia.org/wiki/Application_programming_interface
