= Java serialization ways: Performance Comparison
2014/05/13 17:00:00
:toc:

[abstract]
== Abstract
Java serialization ways, performance comparison

Recently I've had to serialize/deserialize some data in link:[Java] binary format. Lately I use link:[JSON] or link:[XML] formats.

I remember that to serialize link:[Java] objects they must implement the link:#serializable[Serializable] interface, but I had also read in Internet other way, implementing the link:#externalizable[Externalizable] interface, then, which interface must I implement? It depends on what you want such as everything in the life.

When to use link:#serializable[Serializable] or link:#externalizable[Externalizable]

== link:#serializable[Serializable]

* To serialize easily. You have to write less code.
* This way has some restrictions: The object to serialize must implement the default constructor (0 args). It must be responsible to manage the parent class attributes.
* The performance is not as important, we will see more about that in link:#performance-tests-serializable-vs.-externalizable[Performance tests (Serializable vs. Externalizable)].

== link:#externalizable[Externalizable]

* You must implement the serialization/deserialization methods, so you have to write more code.
* When you cannot use link:#serializable[Serializable].
* When you want to improve the performance, as we'll see in link:#performance-tests-serializable-vs.-externalizable[Performance tests (Serializable vs. Externalizable)]
* If you have to manage the serialization of parent class attributes, then I recommend you use link:#externalizable[Externalizable], because we'll avoid a weird overriding of private methods.

[source,java]
----
private void writeObject(ObjectOutputStream oos)
private void readObject(ObjectInputStream ois)
----

== Performance tests (Serializable vs. Externalizable)

link:#serializable[Serializable]: Java, through introspection, guesses the types of class attributes to know how to serialize/deserialize them, but this "magic" is not free, it has a performance penalty.

When we use link:#externalizable[Externalizable] interface, we decide how to serialize/deserialize, namely we have to write the code that does it. We've lost ease, but also we avoid that link:[Java] does some tasks, so if we override the methods properly, we'll get a performance improvement.

To know how much is the performance difference between both interfaces, I've written a https://carlosvin.github.io/serializations-performance-java/[tiny example in which we serialize an object with 2 collections with 100000 elements each one], 3 ways:

=== Implementing link:#serializable[Serializable]

As we told above, link:[Java] has to guessed certain things, in this process it sacrifices some of performance (slower way), in exchange for programming simplicity, the class to serialize just has to implement the link:#serializable[Serializable] interface.

[source,java]
----
public class Contacts implements Serializable {
----

* serializing: 1133 millisecond
* deserializing: 506 millisecond

=== Implementing link:#externalizable[Externalizable] (wrong way)

If the class implements link:#externalizable[Externalizable], we must tell to link:[Java] how it has to serialize/deserialize the class attributes. We must be carefully, because if we did it bad, then we'll get the worst of the both worlds: more complex implementation and bad performance, i.e: If we serialize/deserialize complex class attributes (like collections), link:[Java] will also have to guess many things about the attributes type.

[source,java]
----
@Override
public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
  setEmails((Set<String>) in.readObject());
  setPhones((Set<String>) in.readObject());
}

@Override
public void writeExternal(ObjectOutput out) throws IOException {
  out.writeObject(emails);
  out.writeObject(phones);
}
----

* serializing: 737 millisecond
* deserializing: 367 millisecond

=== Implementing link:#externalizable[Externalizable] (right way)

If we serialize one by one the collection elements, then we'll save more time, because link:[Java] serializes simple types, this way avoids guessing things that we actually know.

[source,java]
----
@Override
public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
  emails.clear();
  phones.clear();
  int nEmails = in.readInt();
  for (int i = 0; i < nEmails; i++) {
    emails.add(in.readUTF());
  }
  int nPhones = in.readInt();
  for (int i = 0; i < nPhones; i++) {
    phones.add(in.readUTF());
  }
}

@Override
public void writeExternal(ObjectOutput out) throws IOException {
  out.writeInt(emails.size());
  for (String e : emails) {
    out.writeUTF(e);
  }
  out.writeInt(phones.size());
  for (String p : phones) {
    out.writeUTF(p);
  }
}
----

* serializing: 204 millisecond
* deserializing: 92 millisecond

We've gained performance at expense of write more code.

=== Result Analysis

[CAUTION]
.Caution
====
We don't gain performance due to use an interface or the other one.
====[TIP]
.Tip
====
We gain performance because link:#externalizable[Externalizable] interface forces us to implement ourselves the guessing code, so link:[Java] doesn't have to do that.
====Although as we have watched in link:#implementing-externalizable-right-way[Implementing Externalizable (right way)], if we wouldn't be careful in implementation, we'll get less performance.

Following you can see a link:[graph] with https://carlosvin.github.io/serializations-performance-java/reports/tests/classes/com.diky.contacts.SerializationTest.html[Tests results].

image:https://docs.google.com/spreadsheets/d/1V9p6shPMpSr7RcaTruXpj_0ZQUpVjMFdeh7AnObaBL8/embed/oimg?id=1V9p6shPMpSr7RcaTruXpj_0ZQUpVjMFdeh7AnObaBL8&oid=2110613848&zx=t87gu6ve3lan[Open interactive link:[graph] | link:[Open image],scaledwidth=80.0%]

* https://carlosvin.github.io/serializations-performance-java/reports/tests/classes/com.diky.contacts.SerializationTest.html[Tests results].
* https://github.com/carlosvin/serializations-performance-java/[Code in Github].
* link:[Travis CI build status]
+
image:https://travis-ci.org/carlosvin/serializations-performance-java.svg?branch=master[image]

_Java::
  https://www.java.com/
_JSON::
  https://www.json.org/
_XML::
  https://en.wikipedia.org/wiki/XML
_Serializable::
  https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html
_Externalizable::
  https://docs.oracle.com/javase/7/docs/api/java/io/Externalizable.html
