on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v5.0.0
      - name: 'build'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: pages
          BUILD_DIR: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_ONLY: true
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: 'checkout'
      uses: actions/checkout@v5.0.0
    - name: 'build and deploy'
      uses: shalzz/zola-deploy-action@v0.21.0
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: .
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: carlosvin/carlosvin.github.io
    - name: Notify IndexNow
      run: curl -o /dev/null -w "%{http_code}\n" "https://api.indexnow.org/indexnow?url=https://carlosvin.github.io&key=58k0hy1db4"